(define (deep-reverse items)
  (define (iter items result)
    (if (null? items)
      result
      (iter (cdr items)
            (cons (deep-reverse (car items))
                  result))))
  (if (pair? items)
    (iter items '())
    items))
