(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((consecutive-mistakes 0) (limit 7))
    (define (dispatch pw m)
      (if (eq? pw password)
        (begin (set! consecutive-mistakes 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request -- MAKE-ACCOUNT" m))))
        (begin (set! consecutive-mistakes (+ consecutive-mistakes 1))
               (if (>= consecutive-mistakes limit) (call-the-cops))
               (lambda (x) "Incorrect password"))))
    dispatch))
