(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pw m)
    (if (eq? pw password)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT" m)))
      (lambda (x) "Incorrect password")))
  dispatch)

(define (make-joint account old-password new-password)
  (define (dispatch pw m)
    (if (eq? pw new-password)
      (account old-password m)
      (lambda (x) "Incorrect password")))
  dispatch)
